### ISSUE TITLE
Support for connection to host with password?

### ISSUE THREAD

**Issue by nathvi** [dburriss/serilog-sinks-redis#17]
How do you connect to a host with a password?

**Comment by rpiesnikowski** [comment]
Under the hood Redis Sink uses `ConfigurationOptions.Parse(redisUris)` to resolve configuration. To connect with your host with password you need to set `redisUris `as `password=foobared,defaultDatabase=3,127.0.0.1:6379`. 
For reference see: https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/ConfigurationOptions.cs#L550 - this is how Redis Sink configure connection to redis.

**Comment by nathvi** [comment]
Nevermind, I just wrote my own redis sink anyway. I'm just passing it a RedisClient object. Seems more natural.

**Comment by dburriss** [comment]
@nathvi Sorry for the late reply. I must have missed the email. I am glad you came right. 
I try avoid exposing implementation details.
