### ISSUE TITLE
Configuration in appsettings.json Asp.net core 2.1

### ISSUE THREAD

**Issue by ParagNaikade** [dburriss/serilog-sinks-redis#20]
I am getting following exception:

System.TypeLoadException: 'Method 'get_IsConnecting' in type 'Serilog.Sinks.Redis.List.NoConnectionMultiplexer' from assembly 'Serilog.Sinks.Redis.List, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

This is my code:
var logger = new LoggerConfiguration()
                            .WriteTo.RedisList("localhost:6379", "testKey")
                            .ReadFrom.Configuration(Configuration)
                            .CreateLogger();

I am using Serilog.Sinks.Redis.List version 1.3.1

**Comment by dburriss** [comment]
What version of .NET are you targeting?Maybe post relevant parts of csproj or a minimal repro?

**Comment by ParagNaikade** [comment]
Its .net core 2.1. I have asp.net core web api project, in which, in Program.cs file, i am trying to configure the logger. At this ".WriteTo.RedisList()", it throws exception.

**Comment by knepe** [comment]
I have the same issue in .net core 2.2
For me, it seems to boil down to upgrading CacheManager.StackExchange.Redis to 1.2.0. If I downgrade to 1.1.2 it works.

**Comment by dburriss** [comment]
Thanks for the info @knepe 
I will try do an upgrade of this project to whatever the latest supported by the Redis client.
It is not used by myself or the previous company so if you want to start submitting PRs to keep it up to date that would be appreciated.
